import 'package:flutter/material.dart';

class Themes {
  static ThemeData customTheme = ThemeData(
    applyElevationOverlayColor: false,
    brightness: Brightness.light,
    buttonTheme: const ButtonThemeData(
      alignedDropdown: false,
      colorScheme: ColorScheme.light(
        background: Color(0xfffdfcff),
        error: Color.fromARGB(255, 255, 26, 26),
        errorContainer: Color(0xffffdad6),
        primary: Color.fromARGB(255, 40, 43, 138),
        primaryContainer: Color(0xffd1e4ff),
        secondary: Color(0xff535f70),
        secondaryContainer: Color(0xffd7e3f7),
        surface: Color(0xfffdfcff),
        surfaceTint: Color.fromARGB(255, 40, 43, 138),
      ),
      height: 36,
      layoutBehavior: ButtonBarLayoutBehavior.padded,
      minWidth: 88,
      padding: EdgeInsets.only(left: 16, right: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.only(
          bottomLeft: Radius.elliptical(2, 2),
          bottomRight: Radius.elliptical(2, 2),
          topLeft: Radius.elliptical(2, 2),
          topRight: Radius.elliptical(2, 2),
        ),
      ),
      textTheme: ButtonTextTheme.normal,
    ),
    canvasColor: const Color(0xfffdfcff),
    cardColor: const Color(0xfffdfcff),
    colorScheme: const ColorScheme.light(
      background: Color(0xfffdfcff),
      error: Color.fromARGB(255, 255, 26, 26),
      errorContainer: Color(0xffffdad6),
      primary: Color.fromARGB(255, 40, 43, 138),
      primaryContainer: Color(0xffd1e4ff),
      secondary: Color(0xff535f70),
      secondaryContainer: Color(0xffd7e3f7),
      surface: Color(0xfffdfcff),
      surfaceTint: Color.fromARGB(255, 40, 43, 138),
    ),
    dialogBackgroundColor: const Color(0xfffdfcff),
    disabledColor: const Color(0x61000000),
    dividerColor: const Color(0xff1a1c1e),
    focusColor: const Color(0x1f000000),
    highlightColor: const Color(0x66bcbcbc),
    hintColor: const Color(0x99000000),
    hoverColor: const Color(0x0a000000),
    iconTheme: const IconThemeData(
      color: Color(0xdd000000),
    ),
    indicatorColor: const Color(0xffffffff),
    inputDecorationTheme: const InputDecorationTheme(
      alignLabelWithHint: false,
      filled: false,
      floatingLabelBehavior: FloatingLabelBehavior.auto,
      isCollapsed: false,
      isDense: false,
    ),
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    platform: TargetPlatform.macOS,
    primaryColor: const Color.fromARGB(255, 40, 43, 138),
    primaryColorDark: const Color(0xff1976d2),
    primaryColorLight: const Color(0xffbbdefb),
    primaryIconTheme: const IconThemeData(
      color: Color(0xffffffff),
    ),
    primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    scaffoldBackgroundColor: const Color(0xfffdfcff),
    secondaryHeaderColor: const Color(0xffe3f2fd),
    shadowColor: const Color(0xff000000),
    splashColor: const Color(0x66c8c8c8),
    splashFactory: InkRipple.splashFactory,
    textTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xdd000000),
        decoration: TextDecoration.none,
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    unselectedWidgetColor: const Color(0x8a000000),
    useMaterial3: false,
    visualDensity: VisualDensity.compact,
  );
}
